package server.controller;

public enum Lock {
    IO_LOCK, CATEGORY_LOCK, EDITING_PRODUCT_LOCK, ADMIN_MODIFY_PRODUCT_LOCK,
    ADMIN_MODIFY_EDIT_PRODUCT_LOCK, PRODUCT_FILE_LOCK, EDITING_PRODUCT_FILE_LOCK,
    PRODUCT_IMAGE_LOCK, EDITING_PRODUCT_IMAGE_LOCK;
}
